-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 21:45:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ToodDatabase` DEFAULT CHARACTER SET utf8 ;
USE `ToodDatabase` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToodDatabase`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `cnpj` CHAR(14) NULL,
  `telefone` VARCHAR(13) NULL,
  `responsavel` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToodDatabase`.`Estabelecimento` (
  `idEstabelecimento` INT NOT NULL,
  `fkEmpresa` INT NOT NULL,
  `identificacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstabelecimento`),
  CONSTRAINT `fk_Freezer_Empresa1`
    FOREIGN KEY (`fkEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Totem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToodDatabase`.`Totem` (
  `idTotem` INT NOT NULL,
  `fkEstabelecimento` INT NOT NULL,
  `processador` VARCHAR(45) NULL,
  `ram` VARCHAR(45) NULL,
  `gpu` VARCHAR(45) NULL,
  `disco` VARCHAR(45) NULL,
  PRIMARY KEY (`idTotem`, `fkEstabelecimento`),
  CONSTRAINT `fk_Totem_Estabelecimento1`
    FOREIGN KEY (`fkEstabelecimento`)
    REFERENCES `mydb`.`Estabelecimento` (`idEstabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`DadoTotem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToodDatabase`.`DadoTotem` (
  `idDadosTotem` INT NOT NULL,
  `fkTotem` INT NOT NULL,
  `dataHora` DATETIME NULL,
  `statusRam` VARCHAR(45) NULL,
  `statusGpu` VARCHAR(45) NULL,
  `statusDisco` VARCHAR(45) NULL,
  PRIMARY KEY (`idDadosTotem`, `fkTotem`),
  CONSTRAINT `fk_dados_sensores`
    FOREIGN KEY (`fkTotem`)
    REFERENCES `mydb`.`Totem` (`idTotem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToodDatabase`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `fkEmpresa` INT NOT NULL,
  `nomeUsuario` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL,
  `senha` VARCHAR(16) NULL,
  PRIMARY KEY (`idUsuario`, `fkEmpresa`),
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`fkEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`AlertaSensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToodDatabase`.`AlertaSensor` (
  `idAlertaSensor` INT NOT NULL,
  `fkSensor` INT NOT NULL,
  `dtAlerta` DATETIME NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlertaSensor`, `fkSensor`),
  CONSTRAINT `fk_Alerta_has_Sensores_Sensores1`
    FOREIGN KEY (`fkSensor`)
    REFERENCES `mydb`.`Totem` (`idTotem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
